### ISSUE TITLE
Recording Web camera stream ( V4L2 ) while display the video.

### ISSUE THREAD

**Issue by FPGA-KING** [kibsoft/QtMEL#44]
Hello. Now days we have research about media application based on QT, LINUX.

Some difficulty about the application is that recording a video is easy and 

display the video also easy. But it is different when I do the jobs same time.

Could you help me? is the library suitable for my application?

Thanks.

**Comment by kibsoft** [comment]
Hello. The project is not maintained since 2016, so there is no guarantee it will work with the newest versions of Qt and FFMpeg.
As far as I remember there were only some troubles with audio/video sync from web cameras, but if you only wanna grab video then you can look into the QtMEL sources. Check out cameragrabber.h/.cpp.

**Comment by kibsoft** [comment]
If you need to grab your screen then look at the screengrabber.h/.cpp

**Comment by FPGA-KING** [comment]
Thanks a lot for quick response.
